[package]
name = "dns-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dns-macros = {path="../dns-macros"}

ux = "0.1.5"
